name: Coverage

on:
  push:
    paths-ignore:
     - 'docs/**'
     - 'README.md'
    branches:
      - master

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
    - name: Code Coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
        debug: true